# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detection.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DetectionWindow(object):
    def setupUi(self, DetectionWindow):
        DetectionWindow.setObjectName("DetectionWindow")
        DetectionWindow.resize(800, 480)
        self.centralwidget = QtWidgets.QWidget(DetectionWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.refresh_button = QtWidgets.QPushButton(self.centralwidget)
        self.refresh_button.setGeometry(QtCore.QRect(160, 350, 111, 41))
        self.refresh_button.setStyleSheet("QPushButton {\n"
"    background-color: #42A5F5;\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 12px; /* 调整字体大小 */\n"
"    font-weight: bold;\n"
"    border: none; /* 取消边框 */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: darkgreen;\n"
"}    ")
        self.refresh_button.setObjectName("refresh_button")
        self.close_button = QtWidgets.QPushButton(self.centralwidget)
        self.close_button.setGeometry(QtCore.QRect(530, 350, 101, 41))
        self.close_button.setStyleSheet("QPushButton {\n"
"    background-color: #42A5F5;\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 12px; /* 调整字体大小 */\n"
"    font-weight: bold;\n"
"    border: none; /* 取消边框 */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: darkgreen;\n"
"}    ")
        self.close_button.setObjectName("close_button")
        self.table_view = QtWidgets.QTableView(self.centralwidget)
        self.table_view.setGeometry(QtCore.QRect(30, 10, 721, 311))
        self.table_view.setStyleSheet("QTableView {\n"
"    background-color: #f0f0f0; /* 浅灰色背景 */\n"
"    color: #007BFF; /* 蓝色文字 */\n"
"    gridline-color: #ccc; /* 灰色网格线 */\n"
"}\n"
"\n"
"QTableView::item {\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"    background-color: #007BFF; /* 蓝色选中背景 */\n"
"    color: white; /* 白色选中文字 */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #e0e0e0; /* 稍深的灰色表头背景 */\n"
"    color: #007BFF; /* 蓝色表头文字 */\n"
"    border: 1px solid #ccc; /* 灰色表头边框 */\n"
"    padding: 5px;\n"
"}")
        self.table_view.setObjectName("table_view")
        DetectionWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DetectionWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        DetectionWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DetectionWindow)
        self.statusbar.setObjectName("statusbar")
        DetectionWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DetectionWindow)
        QtCore.QMetaObject.connectSlotsByName(DetectionWindow)

    def retranslateUi(self, DetectionWindow):
        _translate = QtCore.QCoreApplication.translate
        DetectionWindow.setWindowTitle(_translate("DetectionWindow", "MainWindow"))
        self.refresh_button.setText(_translate("DetectionWindow", "刷新"))
        self.close_button.setText(_translate("DetectionWindow", "关闭"))
