# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(140, 140, 531, 141))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.view_detection_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.view_detection_button.setStyleSheet("QPushButton {\n"
"    background-color: lightblue;\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 12px; /* 调整字体大小 */\n"
"    font-weight: bold;\n"
"    border: none; /* 取消边框 */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: darkgreen;\n"
"} ")
        self.view_detection_button.setObjectName("view_detection_button")
        self.horizontalLayout.addWidget(self.view_detection_button)
        self.testButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.testButton.setStyleSheet("QPushButton {\n"
"    background-color: lightblue;\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 12px; /* 调整字体大小 */\n"
"    font-weight: bold;\n"
"    border: none; /* 取消边框 */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: darkgreen;\n"
"} ")
        self.testButton.setObjectName("testButton")
        self.horizontalLayout.addWidget(self.testButton)
        self.data_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.data_Button.setStyleSheet("QPushButton {\n"
"    background-color: lightblue;\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 12px; /* 调整字体大小 */\n"
"    font-weight: bold;\n"
"    border: none; /* 取消边框 */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: darkgreen;\n"
"} ")
        self.data_Button.setObjectName("data_Button")
        self.horizontalLayout.addWidget(self.data_Button)
        self.settingButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.settingButton.setStyleSheet("QPushButton {\n"
"    background-color: lightblue;\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 12px; /* 调整字体大小 */\n"
"    font-weight: bold;\n"
"    border: none; /* 取消边框 */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: darkgreen;\n"
"} ")
        self.settingButton.setObjectName("settingButton")
        self.horizontalLayout.addWidget(self.settingButton)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(640, 350, 101, 31))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: lightblue;\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 12px; /* 调整字体大小 */\n"
"    font-weight: bold;\n"
"    border: none; /* 取消边框 */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: darkgreen;\n"
"} ")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 50, 451, 61))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.view_detection_button.setText(_translate("MainWindow", "批量测试"))
        self.testButton.setText(_translate("MainWindow", "测试"))
        self.data_Button.setText(_translate("MainWindow", "项目"))
        self.settingButton.setText(_translate("MainWindow", "设置"))
        self.pushButton_6.setText(_translate("MainWindow", "关机"))
        self.label_2.setText(_translate("MainWindow", "欢迎使用荧光分析仪"))
