# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'text.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TextWindow(object):
    def setupUi(self, TextWindow):
        TextWindow.setObjectName("TextWindow")
        TextWindow.resize(800, 480)
        self.centralwidget = QtWidgets.QWidget(TextWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 40, 351, 131))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(680, 10, 75, 23))
        self.back_button.setStyleSheet("QPushButton {\n"
"    background-color: #42A5F5;\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 12px; /* 调整字体大小 */\n"
"    font-weight: bold;\n"
"    border: none; /* 取消边框 */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    min-width: 65px; /* 设置最小宽度 */\n"
"    max-width: 65px; /* 设置最大宽度 */\n"
"    min-height: 13px; /* 设置最小高度 */\n"
"    max-height: 13px; /* 设置最大高度 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: darkgreen;\n"
"}    ")
        self.back_button.setObjectName("back_button")
        self.calc_button = QtWidgets.QPushButton(self.centralwidget)
        self.calc_button.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.calc_button.setStyleSheet("QPushButton {\n"
"    background-color: #42A5F5;\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 12px; /* 调整字体大小 */\n"
"    font-weight: bold;\n"
"    border: none; /* 取消边框 */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    min-width: 65px; /* 设置最小宽度 */\n"
"    max-width: 65px; /* 设置最大宽度 */\n"
"    min-height: 13px; /* 设置最小高度 */\n"
"    max-height: 13px; /* 设置最大高度 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: darkgreen;\n"
"}    ")
        self.calc_button.setObjectName("calc_button")
        TextWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TextWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        TextWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TextWindow)
        self.statusbar.setObjectName("statusbar")
        TextWindow.setStatusBar(self.statusbar)

        self.retranslateUi(TextWindow)
        QtCore.QMetaObject.connectSlotsByName(TextWindow)

    def retranslateUi(self, TextWindow):
        _translate = QtCore.QCoreApplication.translate
        TextWindow.setWindowTitle(_translate("TextWindow", "MainWindow"))
        self.label.setText(_translate("TextWindow", "峰面积比:"))
        self.back_button.setText(_translate("TextWindow", "返回"))
        self.calc_button.setText(_translate("TextWindow", "计算"))
