# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.load_user_button = QtWidgets.QPushButton(self.centralwidget)
        self.load_user_button.setGeometry(QtCore.QRect(120, 80, 211, 31))
        self.load_user_button.setStyleSheet("QPushButton {\n"
"    background-color: #42A5F5;\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 12px; /* 调整字体大小 */\n"
"    font-weight: bold;\n"
"    border: none; /* 取消边框 */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: darkgreen;\n"
"}    ")
        self.load_user_button.setObjectName("load_user_button")
        self.view_detection_button = QtWidgets.QPushButton(self.centralwidget)
        self.view_detection_button.setGeometry(QtCore.QRect(120, 280, 211, 31))
        self.view_detection_button.setStyleSheet("QPushButton {\n"
"    background-color: #42A5F5;\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 12px; /* 调整字体大小 */\n"
"    font-weight: bold;\n"
"    border: none; /* 取消边框 */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: darkgreen;\n"
"}    ")
        self.view_detection_button.setObjectName("view_detection_button")
        self.insert_user_button = QtWidgets.QPushButton(self.centralwidget)
        self.insert_user_button.setGeometry(QtCore.QRect(120, 120, 211, 31))
        self.insert_user_button.setStyleSheet("QPushButton {\n"
"    background-color: #42A5F5;\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 12px; /* 调整字体大小 */\n"
"    font-weight: bold;\n"
"    border: none; /* 取消边框 */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: darkgreen;\n"
"}    ")
        self.insert_user_button.setObjectName("insert_user_button")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(120, 320, 211, 31))
        self.back_button.setStyleSheet("QPushButton {\n"
"    background-color: #42A5F5;\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 12px; /* 调整字体大小 */\n"
"    font-weight: bold;\n"
"    border: none; /* 取消边框 */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: darkgreen;\n"
"}    ")
        self.back_button.setObjectName("back_button")
        self.query_button = QtWidgets.QPushButton(self.centralwidget)
        self.query_button.setGeometry(QtCore.QRect(360, 80, 371, 31))
        self.query_button.setStyleSheet("QPushButton {\n"
"    background-color: #42A5F5;\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 12px; /* 调整字体大小 */\n"
"    font-weight: bold;\n"
"    border: none; /* 取消边框 */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: darkgreen;\n"
"}    ")
        self.query_button.setObjectName("query_button")
        self.age_input = QtWidgets.QLineEdit(self.centralwidget)
        self.age_input.setGeometry(QtCore.QRect(170, 159, 161, 31))
        self.age_input.setStyleSheet("    background-color: #f0f0f0; /* 浅灰色背景 */\n"
"    color: black;")
        self.age_input.setText("")
        self.age_input.setObjectName("age_input")
        self.username_input = QtWidgets.QLineEdit(self.centralwidget)
        self.username_input.setGeometry(QtCore.QRect(170, 200, 161, 31))
        self.username_input.setStyleSheet("    background-color: #f0f0f0; /* 浅灰色背景 */\n"
"    color: black;")
        self.username_input.setObjectName("username_input")
        self.email_input = QtWidgets.QLineEdit(self.centralwidget)
        self.email_input.setGeometry(QtCore.QRect(170, 240, 161, 31))
        self.email_input.setStyleSheet("    background-color: #f0f0f0;\n"
"    color: black;")
        self.email_input.setObjectName("email_input")
        self.table_view = QtWidgets.QTableView(self.centralwidget)
        self.table_view.setGeometry(QtCore.QRect(360, 160, 371, 191))
        self.table_view.setStyleSheet("QTableView {\n"
"    background-color: #f0f0f0; /* 浅灰色背景 */\n"
"    color: #007BFF; /* 蓝色文字 */\n"
"    gridline-color: #ccc; /* 灰色网格线 */\n"
"}\n"
"\n"
"QTableView::item {\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"    background-color: #007BFF; /* 蓝色选中背景 */\n"
"    color: white; /* 白色选中文字 */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #e0e0e0; /* 稍深的灰色表头背景 */\n"
"    color: #007BFF; /* 蓝色表头文字 */\n"
"    border: 1px solid #ccc; /* 灰色表头边框 */\n"
"    padding: 5px;\n"
"}")
        self.table_view.setObjectName("table_view")
        self.query_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.query_combobox.setGeometry(QtCore.QRect(360, 120, 371, 31))
        self.query_combobox.setStyleSheet("QComboBox {\n"
"    background-color: #f0f0f0; /* 浅灰色背景 */\n"
"    color: black;\n"
"    border: 1px solid #ccc; /* 浅灰色边框 */\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: #ccc; /* 浅灰色边框 */\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    background-color: #f0f0f0; /* 浅灰色背景 */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid #ccc; /* 浅灰色边框 */\n"
"    selection-background-color: #e0e0e0; /* 选中项的浅灰色背景 */\n"
"    background-color: #f0f0f0; /* 下拉列表的浅灰色背景 */\n"
"    color: black;\n"
"}")
        self.query_combobox.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.query_combobox.setObjectName("query_combobox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 162, 40, 31))
        self.label.setStyleSheet("    background-color: #42A5F5;\n"
"    color: black;\n"
"    font-family: Arial;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"\n"
"    text-align: center;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 200, 40, 31))
        self.label_2.setStyleSheet("    background-color: #42A5F5;\n"
"    color: black;\n"
"    font-family: Arial;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    text-align: center;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 240, 40, 31))
        self.label_3.setStyleSheet("    background-color: #42A5F5;\n"
"    color: black;\n"
"    font-family: Arial;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    text-align: center;")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.load_user_button.setText(_translate("MainWindow", "从文件中选择对象"))
        self.view_detection_button.setText(_translate("MainWindow", "查看检测按钮"))
        self.insert_user_button.setText(_translate("MainWindow", "插入用户"))
        self.back_button.setText(_translate("MainWindow", "返回主界面"))
        self.query_button.setText(_translate("MainWindow", "查询对象"))
        self.label.setText(_translate("MainWindow", "年龄"))
        self.label_2.setText(_translate("MainWindow", "名字"))
        self.label_3.setText(_translate("MainWindow", "邮箱"))
