# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        MainWindow.setWindowOpacity(0.0)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 80, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(440, 80, 41, 20))
        self.label_2.setMaximumSize(QtCore.QSize(16777210, 16777215))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(80, 120, 601, 101))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 1, 211, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("    background-color: #42A5F5;\n"
"    color: black;\n"
"    font-family: Arial;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    text-align: center;")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setStyleSheet("    border: 1px solid #BDBDBD; /* 浅灰色边框 */\n"
"    border-radius: 3px;\n"
"    padding: 3px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("    background-color: #42A5F5;\n"
"    color: black;\n"
"    font-family: Arial;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    text-align: center;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setStyleSheet("    border: 1px solid #BDBDBD; /* 浅灰色边框 */\n"
"    border-radius: 3px;\n"
"    padding: 3px;")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("    background-color: #42A5F5;\n"
"    color: black;\n"
"    font-family: Arial;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    text-align: center;")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setStyleSheet("")
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(240, 20, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("QRadioButton {\n"
"    font-size: 12px;\n"
"}\n"
"QRadioButton::indicator {\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    border: 1px solid #BDBDBD;\n"
"    border-radius: 7px;\n"
"    background-color: white;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #2196F3;\n"
"}")
        self.radioButton.setObjectName("radioButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(360, 10, 111, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setGeometry(QtCore.QRect(0, 30, 89, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("QRadioButton {\n"
"    font-size: 12px;\n"
"}\n"
"QRadioButton::indicator {\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    border: 1px solid #BDBDBD;\n"
"    border-radius: 7px;\n"
"    background-color: white;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #2196F3;\n"
"}")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_3.setGeometry(QtCore.QRect(0, 50, 89, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setStyleSheet("QRadioButton {\n"
"    font-size: 12px;\n"
"}\n"
"QRadioButton::indicator {\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    border: 1px solid #BDBDBD;\n"
"    border-radius: 7px;\n"
"    background-color: white;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #2196F3;\n"
"}")
        self.radioButton_3.setObjectName("radioButton_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(510, 10, 81, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(10, 40, 54, 12))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(240, 60, 101, 31))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #42A5F5;\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 12px; /* 调整字体大小 */\n"
"    font-weight: bold;\n"
"    border: none; /* 取消边框 */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: darkgreen;\n"
"}    ")
        self.pushButton.setObjectName("pushButton")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(80, 240, 451, 91))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(30, 10, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setToolTipDuration(-1)
        self.label_7.setStyleSheet("QLabel {\n"
"    font-family: Arial;\n"
"    font-size: 12px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QLabel#importantLabel {\n"
"    font-weight: bold;\n"
"    color: #2196F3;\n"
"}")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(20, 50, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel {\n"
"    font-family: Arial;\n"
"    font-size: 12px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QLabel#importantLabel {\n"
"    font-weight: bold;\n"
"    color: #2196F3;\n"
"}")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(230, 10, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel {\n"
"    font-family: Arial;\n"
"    font-size: 12px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QLabel#importantLabel {\n"
"    font-weight: bold;\n"
"    color: #2196F3;\n"
"}")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setGeometry(QtCore.QRect(230, 50, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(570, 300, 51, 31))
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #42A5F5;\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 9px; /* 调整字体大小 */\n"
"    font-weight: bold;\n"
"    border: none; /* 取消边框 */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: darkgreen;\n"
"}    ")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(630, 300, 51, 31))
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: #42A5F5;\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 12px; /* 调整字体大小 */\n"
"    font-weight: bold;\n"
"    border: none; /* 取消边框 */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: darkgreen;\n"
"}    ")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(570, 350, 111, 31))
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #42A5F5;\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 12px; /* 调整字体大小 */\n"
"    font-weight: bold;\n"
"    border: none; /* 取消边框 */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: darkgreen;\n"
"}    ")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(100, 340, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("    background-color: #42A5F5;\n"
"    color: black;\n"
"    font-family: Arial;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    text-align: center;")
        self.label_11.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.HongKong))
        self.label_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_11.setObjectName("label_11")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(170, 340, 361, 51))
        self.textBrowser.setObjectName("textBrowser")
        self.main_button = QtWidgets.QPushButton(self.centralwidget)
        self.main_button.setGeometry(QtCore.QRect(630, 250, 51, 31))
        self.main_button.setMinimumSize(QtCore.QSize(0, 0))
        self.main_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.main_button.setToolTipDuration(0)
        self.main_button.setStyleSheet("QPushButton {\n"
"    background-color: #42A5F5;\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 12px; /* 调整字体大小 */\n"
"    font-weight: bold;\n"
"    border: none; /* 取消边框 */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: darkgreen;\n"
"}    ")
        self.main_button.setObjectName("main_button")
        self.fluo_button = QtWidgets.QPushButton(self.centralwidget)
        self.fluo_button.setGeometry(QtCore.QRect(570, 250, 51, 31))
        self.fluo_button.setMinimumSize(QtCore.QSize(0, 0))
        self.fluo_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fluo_button.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.fluo_button.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.fluo_button.setStyleSheet("QPushButton {\n"
"    background-color: #42A5F5;\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 12px; /* 调整字体大小 */\n"
"    font-weight: bold;\n"
"    border: none; /* 取消边框 */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: darkgreen;\n"
"}    ")
        self.fluo_button.setObjectName("fluo_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "干式荧光免疫分析仪"))
        self.label_2.setText(_translate("MainWindow", "测试"))
        self.label_4.setText(_translate("MainWindow", "流水号："))
        self.label_3.setText(_translate("MainWindow", "样本号："))
        self.label_5.setText(_translate("MainWindow", "样本类型："))
        self.radioButton.setText(_translate("MainWindow", "使用扫码枪"))
        self.groupBox_2.setTitle(_translate("MainWindow", "测试方法"))
        self.radioButton_2.setText(_translate("MainWindow", "即时测试"))
        self.radioButton_3.setText(_translate("MainWindow", "标准测试"))
        self.groupBox_3.setTitle(_translate("MainWindow", "当前用户"))
        self.label_6.setText(_translate("MainWindow", "admin"))
        self.pushButton.setText(_translate("MainWindow", "高级信息"))
        self.label_7.setText(_translate("MainWindow", "样本号："))
        self.label_8.setText(_translate("MainWindow", "测试项目："))
        self.label_9.setText(_translate("MainWindow", "流水号："))
        self.label_10.setText(_translate("MainWindow", "样本类型："))
        self.pushButton_2.setText(_translate("MainWindow", "读ID卡"))
        self.pushButton_3.setText(_translate("MainWindow", "测试"))
        self.pushButton_4.setText(_translate("MainWindow", "打印"))
        self.label_11.setText(_translate("MainWindow", "结果："))
        self.main_button.setText(_translate("MainWindow", "主页"))
        self.fluo_button.setText(_translate("MainWindow", "设置"))
